'use client'

import { useState } from 'react'
import { Save } from 'lucide-react'

const DEFAULT_NAV_ITEMS = [
  { id: 1, labelFr: 'Services', labelEn: 'Services', href: '#services', order: 1, active: true },
    { id: 2, labelFr: 'À propos', labelEn: 'About', href: '#about', order: 2, active: true },
      { id: 3, labelFr: 'Processus', labelEn: 'Process', href: '#process', order: 3, active: true },
        { id: 4, labelFr: 'Témoignages', labelEn: 'Testimonials', href: '#testimonials', order: 4, active: true },
          { id: 5, labelFr: 'Faq', labelEn: 'Faq', href: '#faq', order: 5, active: true },
          ]

          export default function NavigationPage() {
            const [items] = useState(DEFAULT_NAV_ITEMS)
              const [saved, setSaved] = useState(false)

                const handleSave = () => {
                    setSaved(true)
                        setTimeout(() => setSaved(false), 2000)
                          }

                            return (
                                <div>
                                      <div className="flex items-center justify-between mb-6">
                                              <div>
                                                        <h1 className="text-2xl font-bold">Navigation</h1>
                                                                  <p className="text-gray-500 text-sm mt-1">Liens du menu de navigation du site</p>
                                                                          </div>
                                                                                  <button
                                                                                            onClick={handleSave}
                                                                                                      className="flex items-center gap-2 bg-amber-600 text-white px-4 py-2 rounded-lg hover:bg-amber-700"
                                                                                                              >
                                                                                                                        <Save className="w-4 h-4" />
                                                                                                                                  {saved ? 'Sauvegardé !' : 'Sauvegarder'}
                                                                                                                                          </button>
                                                                                                                                                </div>
                                                                                                                                                
                                                                                                                                                      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6">
                                                                                                                                                              <p className="text-amber-800 text-sm">
                                                                                                                                                                        ℹ️ La navigation est définie par les sections du site. Les liens pointent automatiquement vers les sections de la page d'accueil.
                                                                                                                                                                                </p>
                                                                                                                                                                                      </div>
                                                                                                                                                                                      
                                                                                                                                                                                            <div className="bg-white rounded-xl border divide-y">
                                                                                                                                                                                                    {items.map((item) => (
                                                                                                                                                                                                              <div key={item.id} className="flex items-center justify-between p-4">
                                                                                                                                                                                                                          <div className="flex items-center gap-4">
                                                                                                                                                                                                                                        <span className="text-gray-400 text-sm font-mono w-6">{item.order}</span>
                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                      <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                        <span className="font-medium">{item.labelFr}</span>
                                                                                                                                                                                                                                                                                                          <span className="text-gray-400">/</span>
                                                                                                                                                                                                                                                                                                                            <span className="text-gray-500">{item.labelEn}</span>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs text-gray-400 font-mono">{item.href}</span>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                Actif
                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-400 mt-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Pour modifier la navigation, éditez les labels dans la section Contenu ou contactez votre développeur.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
